Repository Na-o-man/Na-o-man_android, pull requests merged in 2024-07, with the labels that each got.

#12 Feat/home UI
  app/src/main/java/com/hgh/na_o_man/presentation/component/groupdetail/CloudButton.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/groupdetail/FolderIcon.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/groupdetail/GroupInfo.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/homeIcon/AddgroupButton.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/homeIcon/GroupList.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/homeIcon/NogroupMessage.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/type/AppBarMenu.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/MainScreen.kt
  app/src/main/res/drawable/ic_button_cloud_138.xml
  app/src/main/res/drawable/ic_button_nav_plus_new_31.xml
  app/src/main/res/drawable/ic_group_detail_folder_body_293.xml
  app/src/main/res/drawable/ic_group_detail_folder_head_122.xml
  app/src/main/res/drawable/ic_group_detail_info_151.xml
  app/src/main/res/drawable/ic_home_no_group_message_299.xml
Labels: ✨feat

#13 Feat/ 포토리스트 , 로그인
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hgh/na_o_man/MainApplication.kt
  app/src/main/java/com/hgh/na_o_man/domain/model/Dummy.kt
  app/src/main/java/com/hgh/na_o_man/presentation/Utill/SocialLoginUtil.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CloudIcon.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/ImageDialog.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/MainAppBar.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/photoImageView.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/type/AppBarMenu.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/GroupDetailActivity.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/GroupDetailScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/photo_list/PhotoListContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/photo_list/PhotoListScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/photo_list/PhotoListViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/MainActivity.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/home/HomeContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignActivity.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignViewModel.kt
  app/src/main/res/drawable/ic_button_check_box_39.xml
  app/src/main/res/drawable/ic_button_close_26.xml
  app/src/main/res/drawable/ic_kakao_login.png
  app/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: 🏴‍☠️fix

#21 Feat/스프린트 1
  app/src/main/java/com/hgh/na_o_man/domain/model/Dummy.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CloudIcon.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CommonBtn.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/Line.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/UserProfile.kt
  app/src/main/java/com/hgh/na_o_man/presentation/theme/Font.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/photo_list/PhotoListScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/MainScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/home/HomeScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignActivity.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignHostScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/ArgeeScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/UploadScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/UserScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/util/ActivityViewModelExt.kt
  app/src/main/java/com/hgh/na_o_man/presentation/util/SocialLoginUtil.kt
  app/src/main/res/drawable/background_1.png
  app/src/main/res/drawable/background_2.png
  app/src/main/res/drawable/background_login.png
  app/src/main/res/drawable/ic_background_agree_276.xml
  app/src/main/res/drawable/ic_check_circle_30.xml
  app/src/main/res/drawable/ic_essential_37.xml
  app/src/main/res/drawable/ic_logo_.png
  app/src/main/res/drawable/ic_no_13.xml
  app/src/main/res/drawable/ic_select_37.xml
  app/src/main/res/drawable/ic_top_cloud_346.xml
  app/src/main/res/drawable/ic_yes_13.xml
  app/src/main/res/drawable/logo.png
Labels: ✨feat, 💄design

#22 스프린트2
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hgh/na_o_man/MainApplication.kt
  app/src/main/java/com/hgh/na_o_man/di/LocalModule.kt
  app/src/main/java/com/hgh/na_o_man/di/RemoteModule.kt
  app/src/main/java/com/hgh/na_o_man/di/util/auth/AccessTokenInterceptor.kt
  app/src/main/java/com/hgh/na_o_man/di/util/auth/Authenticator.kt
  app/src/main/java/com/hgh/na_o_man/di/util/data_store/DataStoreUtil.kt
  app/src/main/java/com/hgh/na_o_man/di/util/remote/ApiHandler.kt
  app/src/main/java/com/hgh/na_o_man/di/util/remote/NetworkStatusChecker.kt
  app/src/main/java/com/hgh/na_o_man/di/util/remote/RetrofitResult.kt
  app/src/main/java/com/hgh/na_o_man/di/util/s3/S3Util.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CloudIcon.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CommonBtn.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/CommonDialog.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/ImageDialog.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/MainAppBar.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/groupdetail/CloudButton.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/GroupDetailFolder/GroupDetailFolderScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/detail/photo_list/PhotoListScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/home/HomeScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignActivity.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SignHostScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/SplashScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/util/OnBottonListener.kt
Labels: ✨feat, 💄design

#29 feat : 로그인 & 회원가입
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/hgh/na_o_man/MainApplication.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/ApiResult.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/auth/request/LoginRequestDto.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/auth/request/SignUpRequestDto.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/auth/response/CheckRegistrationDto.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/auth/response/UserTokenDto.kt
  app/src/main/java/com/hgh/na_o_man/data/dto/common/response/StringDto.kt
  app/src/main/java/com/hgh/na_o_man/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/hgh/na_o_man/data/source/remote/api/AuthService.kt
  app/src/main/java/com/hgh/na_o_man/di/RemoteModule.kt
  app/src/main/java/com/hgh/na_o_man/di/RepositoryModule.kt
  app/src/main/java/com/hgh/na_o_man/di/ServiceModule.kt
  app/src/main/java/com/hgh/na_o_man/di/util/auth/Authenticator.kt
  app/src/main/java/com/hgh/na_o_man/di/util/data_store/DataStoreUtil.kt
  app/src/main/java/com/hgh/na_o_man/di/util/work_manager/ImageUploadWorker.kt
  app/src/main/java/com/hgh/na_o_man/domain/model/auth/AuthInfoModel.kt
  app/src/main/java/com/hgh/na_o_man/domain/model/auth/CheckRegistrationModel.kt
  app/src/main/java/com/hgh/na_o_man/domain/model/auth/UserTokenModel.kt
  app/src/main/java/com/hgh/na_o_man/domain/repository/AuthRepository.kt
  app/src/main/java/com/hgh/na_o_man/domain/usecase/auth/CheckRegistrationUsecase.kt
  app/src/main/java/com/hgh/na_o_man/domain/usecase/auth/LoginAuthUsecase.kt
  app/src/main/java/com/hgh/na_o_man/domain/usecase/auth/SignupAuthUsecase.kt
  app/src/main/java/com/hgh/na_o_man/presentation/component/UserProfile.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/main/mypage/MyPageScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignContract.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/SignViewModel.kt
  app/src/main/java/com/hgh/na_o_man/presentation/ui/sign/signin/UserScreen.kt
  app/src/main/java/com/hgh/na_o_man/presentation/util/SocialLoginUtil.kt
Labels: ✨feat
